### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cid')

### ISSUE THREAD

**Issue by vorburger** [fission-suite/dashboard#46]
https://dashboard.fission.codes remains stuck on https://auth.fission.codes for me. The console shows:

```
basic.ts:55 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cid')
    at basic.ts:55:40
    at async Promise.all (/index 0)
    at async Object.JF (basic.ts:43:17)
    at async Function.fromInfo (PublicTree.ts:78:19)
    at async xn.getDirectChild (PublicTree.ts:167:11)
    at async xn.getOrCreateDirectChild (tree.ts:184:18)
    at async xn.mkdirRecurse (tree.ts:56:19)
    at async xn.mkdirRecurse (tree.ts:63:7)
    at async uc.runOnNode (filesystem.ts:655:16)
    at async uc.mkdir (filesystem.ts:215:5)
```

**Desktop where I'm trying to login:**
 - OS: Fedora Linux
 - Browser: Brave
 - Version: [Version 1.36.112 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/)

**Smartphone where I've approved the login:**
 - Device: 
 - OS: Android
 - Browser: Brave
 - Version: TBD

**Additional context**

When I first tried it, my Brave desktop browser used to have a local built-in IPFS Node activated. That seems to be conflicting with the IPFS Node of my https://dappnode.io. I've meanwhile Disabled Brave Desktop's built-in IPFS Node activated, but it's possible that Fission perhaps somehow got caught up in this and has some sort of corrupt local state? I'm happy to provide any additional information required if it helps you to make it more stable.

**Comment by vorburger** [comment]
FYI I can reproduce it on a New Private Window, which presumably (?) does not share state with the regular one.

**Comment by matheus23** [comment]
Hi @vorburger 👋

This *might* be an instance of a known issue. Can you try running `webnative.leave()` in https://dashboard.fission.codes and re-trying?

If that doesn't fix it and you have another logged-in device around, please try clicking "remove this device" in the auth lobby of the affected device and re-linking.

Please let me know how that goes :+1:

**Comment by vorburger** [comment]
I managed to _remove this device_ on the mobile, and logged in on the desktop browser using that file from the Recovery Kit.

I then tried to login on a New Private Window on the same desktop:

1. open https://auth.fission.codes, which says: _Authenticated as vorburger. Keep this window open if you want to authenticate on another device._
1. Shift-Ctrl-N
2. F12 to get Console
3. Ctrl-L https://dashboard.fission.codes
4. Click _SIGN IN WITH FISSION_
5. It takes you to https://auth.fission.codes/?didExchange=did...
6. Click _Sign In_
7. Type Username and Click _Link account_
8. _Do these numbers match the ones shown on your other device?_
9. click _Approve_ (on the other one)
10. It asks _Allow Dashboard access to the following for about 1 month?_, click _Yes_
11. Same error as above.
12. `webnative.leave()` in Console (of https://auth.fission.codes) makes it say _Authenticated as vorburger_
13. Ctrl-L https://dashboard.fission.codes
14. Click _SIGN IN WITH FISSION_
15. It takes you to https://auth.fission.codes/?didExchange=did...
16. Click _Sign In_
17. It asks _Allow Dashboard access to the following for about 1 month?_, click _Yes_
18. It seems to just "hang" on _Loading your filesystem_ (without any errors on the Console now)
19. I give up after 1 minute or so, and try something else, in the same Dashboard tab of the still Private Window:
20. Ctrl-L https://drive.fission.codes, Click _SIGN IN WITH FISSION_, click _Yes_ to _Allow_
21. Same error as above.
22. `webnative.leave()` in Console (of https://auth.fission.codes) makes it say _Authenticated as vorburger_
23. 20. Ctrl-L https://drive.fission.codes
24. New error, not sure if this is in any way related or a separate bug:

```
decode.js:120 Uncaught (in promise) Error: CBOR decode error: did not find any content to decode
    at tm (decode.js:120:11)
    at Cs (index.js:59:37)
    at Object.$F (encoded.ts:35:17)
    at async basic.ts:54:15
    at async Promise.all (/index 2)
    at async Object.JF (basic.ts:43:17)
    at async Function.fromInfo (PublicTree.ts:78:19)
    at async xn.getDirectChild (PublicTree.ts:167:11)
    at async xn.getOrCreateDirectChild (tree.ts:184:18)
    at async xn.mkdirRecurse (tree.ts:56:19)
```

> This might be an instance of a known issue.

Do you want to link this to another bug? 

It seems to be broken.
